### ISSUE TITLE
老哥能给数据库真实数据吗。

### ISSUE THREAD

**Issue by 1090227412** [ZainZhao/HIS#11]
邮箱1090227412@qq.com  万分感谢!

**Comment by jykSS** [comment]
老哥 我也在跟这个项目 能给份数据库吗 1010158370@qq.com

**Comment by pkyanxm** [comment]
我这边完整跑起来了，可以交流，Q 1522583780

**Comment by wj1234** [comment]
495230459@qq.com  感谢!

**Comment by zyg117** [comment]
老哥能给份数据库吗？万分感谢！ 1170213703@qq.com

**Comment by huangtao261** [comment]
不好意思，我也没有。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zyg117"<notifications@github.com&gt;; 
发送时间: 2020年6月30日(星期二) 下午4:59
收件人: "ZainZhao/HIS"<HIS@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [ZainZhao/HIS] 老哥能给数据库真实数据吗。 (#11)





 
老哥能给份数据库吗？万分感谢！ 1170213703@qq.com
 
&mdash;

**Comment by ZainZhao** [comment]
数据库已经开源，可以看看之前提交的几个版本

**Comment by ZainZhao** [comment]
您好，仓库代码不全部开源，有需求可以联系我邮箱
