### ISSUE TITLE
图片全裂开了

### ISSUE THREAD

**Issue by 666lmj666** [ZainZhao/HIS#37]
请问可以再放一下图片吗？想看看架构，学习学习

**Comment by ZainZhao** [comment]
> 请问可以再放一下图片吗？想看看架构，学习学习

我这没有啊

**Comment by v-yis06** [comment]
> > 请问可以再放一下图片吗？想看看架构，学习学习
> 
> 我这没有啊

大佬，我这边也出现了图片裂开的情况

**Comment by v-yis06** [comment]
跟网络有关系，重新配置下本地机器的hosts可以解决问题，具体可以参考：https://www.cnblogs.com/cckong/p/13727102.html

**Comment by xiaoyonghu** [comment]
> 跟网络有关系，重新配置下本地机器的hosts可以解决问题，具体可以参考：https://www.cnblogs.com/cckong/p/13727102.html

大佬。你们有跑起来吗？可以交流学习一下吗？QQ：3083565734  或者麻烦大佬留个联系方式
