### ISSUE TITLE
请问下pc端是不开源的吗  

### ISSUE THREAD

**Issue by zhang-jia105** [ZainZhao/HIS#38]

**Comment by v-yis06** [comment]
app和web端实现源码都没在项目中看到

**Comment by v-yis06** [comment]
可以移步[TANGKUO/HIS](https://github.com/TANGKUO/HIS.git)这个项目，这个里面有前端代码源码

**Comment by ZainZhao** [comment]
对的，仓库代码不全部开源，有需求可以联系我邮箱
