### ISSUE TITLE
部署过程

### ISSUE THREAD

**Issue by wangmiss** [ZainZhao/HIS#4]
您好，近期会更新部署过程吗？很需要参考

**Comment by ZainZhao** [comment]
近期可能没有太多时间，单体部署的话，建议参考github上的项目mall，部署过程基本相同

**Comment by wangmiss** [comment]
谢谢--谢谢您的回复，麻烦了
在 11月11日 13:49，Zain <notifications@github.com> 写道：
近期可能没有太多时间，单体部署的话，建议参考github上的项目mall，部署过程基本相同



&mdash;
