### ISSUE TITLE
关于项目的疑问

### ISSUE THREAD

**Issue by weiwei5c5** [ZainZhao/HIS#42]
1. 新用户使用APP进行挂号没有病历号不能登录违背常理，看到注释掉的代码，估计是为了赶课设没时间写吧doge）
2. 是否缺少上传ServiceSearchAppApplication模块，好像也没使用到es(捂脸)
3. 小白想部署完整项目只能部署出个大概，希望完善部署教程

**Comment by ZainZhao** [comment]
> 3\. 小白想部署完整项目只能部署出个大概，希望完善部署教程

您好有需求可以联系我微信

1. 可以详细看一下后端生成病例号的逻辑
2. 仓库目前代码不全，es还没有集成
3. 可以联系我邮箱
