### ISSUE TITLE
想要sql    邮箱 yangruiqing991121@163.com

### ISSUE THREAD

**Issue by 1193700079** [ZainZhao/HIS#51]
想要sql   ! 麻烦啦

**Comment by SILENTI** [comment]
sql文件已经没了，丢失了



---原始邮件---
发件人: "Yu ***@***.***&gt;
发送时间: 2022年6月29日(周三) 上午9:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ZainZhao/HIS] 想要sql    邮箱 ***@***.*** (#51)




 
Closed #51 as completed.

**Comment by 1193700079** [comment]
没事没事
