### ISSUE TITLE
演示项目问题

### ISSUE THREAD

**Issue by yangangzhang** [ZainZhao/HIS#6]
演示项目报了一些前端错误，一些页面打不开

**Comment by ZainZhao** [comment]
好的，我正在处理

**Comment by ZainZhao** [comment]
我已重置数据库，已经好使了

**Comment by yangangzhang** [comment]
> 我已重置数据库，已经好使了

![image](https://user-images.githubusercontent.com/20433039/69030858-ae1cc980-0a13-11ea-94dc-2b3c5d5c50f0.png)
vue-router的地方报错了在导航上

**Comment by ZainZhao** [comment]
嗯，我们在做的时候，前端的路由是有一些问题的，但是不影响正常访问

**Comment by yangangzhang** [comment]
> 嗯，我们在做的时候，前端的路由是有一些问题的，但是不影响正常访问

嗯嗯明白了，就是看的一堆警告报错有些别扭，谢谢

**Comment by ZainZhao** [comment]
是的，前端当时的路由是写死的，还有一些字段也没改过来

**Comment by yangangzhang** [comment]
> 是的，前端当时的路由是写死的，还有一些字段也没改过来

项目中没有涉及到接入医保控件的功能吧？

**Comment by ZainZhao** [comment]
没有，只涉及到各类医生的主要业务
